/*
 * This file is generated by jOOQ.
 */
package com.zcg.jooq.learn.codegen;


import com.zcg.jooq.learn.codegen.tables.TUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LearnJooq extends SchemaImpl {

    private static final long serialVersionUID = 1837347405;

    /**
     * The reference instance of <code>learn-jooq</code>
     */
    public static final LearnJooq LEARN_JOOQ = new LearnJooq();

    /**
     * The table <code>learn-jooq.t_user</code>.
     */
    public final TUser T_USER = com.zcg.jooq.learn.codegen.tables.TUser.T_USER;

    /**
     * No further instances allowed
     */
    private LearnJooq() {
        super("learn-jooq", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TUser.T_USER);
    }
}
