/*
 * This file is generated by jOOQ.
 */
package com.zcg.jooq.learn.codegen;


import com.zcg.jooq.learn.codegen.tables.TUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in learn-jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>learn-jooq.t_user</code>.
     */
    public static final TUser T_USER = TUser.T_USER;
}
