/*
 * This file is generated by jOOQ.
 */
package com.zcg.jooq.learn.codegen.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUser implements Serializable {

    private static final long serialVersionUID = -1350571270;

    private Integer userId;
    private String  userName;
    private String  userSex;
    private String  userAddress;
    private String  userPhone;

    public TUser() {}

    public TUser(TUser value) {
        this.userId = value.userId;
        this.userName = value.userName;
        this.userSex = value.userSex;
        this.userAddress = value.userAddress;
        this.userPhone = value.userPhone;
    }

    public TUser(
        Integer userId,
        String  userName,
        String  userSex,
        String  userAddress,
        String  userPhone
    ) {
        this.userId = userId;
        this.userName = userName;
        this.userSex = userSex;
        this.userAddress = userAddress;
        this.userPhone = userPhone;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserSex() {
        return this.userSex;
    }

    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    public String getUserAddress() {
        return this.userAddress;
    }

    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    public String getUserPhone() {
        return this.userPhone;
    }

    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUser (");

        sb.append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(userSex);
        sb.append(", ").append(userAddress);
        sb.append(", ").append(userPhone);

        sb.append(")");
        return sb.toString();
    }
}
